def demo_request
  %q{https://nolb.dhl.de/direct/nexttjlibpublicservlet?xml=%3C?xml%20version=%221.0%22%20encoding=%22ISO-8859-1%22?%3E%3Cdata%20appname=%22%22%20password=%22%22%20language-code=%22de%22%20request=%22d-get-piece-detail%22%20piece-code=%2212345%22%3E%3C/data%3E}
end

def demo_response
  %q{
  <?xml version="1.0" encoding="UTF-8"?>
  <data name="piece-shipment-list" code="0">
  <data name="piece-shipment" error-status="0" piece-id="340433957654312359;0" shipment-code="" piece-identifier="340433957654312359" identifier-type="2" event-location="" event-country="" status-liste="#" status-timestamp="10.09.2010 13:44" status="Die Sendung wurde erfolgreich zugestellt." short-status="Zustellung erfolgreich" recipient-name="Herr Leinweber" recipient-street="Theodor-Loos-Weg 16" recipient-city="12353 Berlin" product-code="00" product-key="" product-name="DHL PAKET" delivery-event-flag="1" recipient-id="3" recipient-id-text="Bevollmächtigter" international-flag="0" piece-code="00340433957654312359" division="DPEED" pan-recipient-name="Sergej Leinweber" pan-recipient-street="Theodor-Loos-Weg 16" pan-recipient-city="12353 Berlin" pan-recipient-address="Theodor-Loos-Weg 16 12353 Berlin" ice="DLVRD" ric="ACCPT" standard-event-code="ZU" shipper-name="Flip4 GmbH" shipper-street="Remscheider Str. 217" shipper-city="42855 Remscheid" shipper-address="Remscheider Str. 217 42855 Remscheid" dest-country="de" origin-country="de" searched-piece-code="00340433957654312359" piece-customer-reference="">
  <data name="piece-event-list" piece-identifier="340433957654312359" _build-time="2011-06-08 07:12:00.000378" piece-id="340433957654312359;0" leitcode="1235304401600">
  <data name="piece-event" event-timestamp="08.09.2010 00:00" event-status="Die Auftragsdaten zu dieser Sendung wurden vom Absender elektronisch an DHL übermittelt." event-text="Die Auftragsdaten zu dieser Sendung wurden vom Absender elektronisch an DHL übermittelt." event-location="" event-country="DE" standard-event-code="VA" ice="PARCV" ric="NRQRD"/>
  <data name="piece-event" event-timestamp="08.09.2010 15:43" event-status="Die Sendung wurde abgeholt." event-text="Die Sendung wurde abgeholt." event-location="" event-country="" standard-event-code="AE" ice="PCKDU" ric="PUBCR"/>
  <data name="piece-event" event-timestamp="08.09.2010 20:13" event-text="Die Sendung wurde im Start-Paketzentrum bearbeitet." event-status="Die Sendung wurde im Start-Paketzentrum bearbeitet." event-location="Rodgau" event-country="DE" standard-event-code="AA" ice="LDTMV" ric="MVMTV"/>
  <data name="piece-event" event-timestamp="10.09.2010 05:12" event-text="Die Sendung wurde im Ziel-Paketzentrum bearbeitet." event-status="Die Sendung wurde im Ziel-Paketzentrum bearbeitet." event-location="Rüdersdorf" event-country="DE" standard-event-code="EE" ice="ULFMV" ric="UNLDD"/>
  <data name="piece-event" event-timestamp="10.09.2010 09:12" event-text="Die Sendung wurde in das Zustellfahrzeug geladen." event-status="Die Sendung wurde in das Zustellfahrzeug geladen." event-location="Berlin-Neukölln" event-country="DE" standard-event-code="PO" ice="SRTED" ric="NRQRD"/>
  <data name="piece-event" event-timestamp="10.09.2010 13:44" event-status="Die Sendung wurde erfolgreich zugestellt." event-text="Die Sendung wurde erfolgreich zugestellt." event-location="" event-country="" standard-event-code="ZU" ice="DLVRD" ric="ACCPT"/>
  </data>
  </data>
  <data name="piece-shipment" error-status="0" piece-id="340433957654312359;1" shipment-code="" piece-identifier="340433957654312359" identifier-type="2" event-location="" event-country="" status-liste="#" status-timestamp="20.05.2011 09:56" status="Die Sendung wurde erfolgreich zugestellt." short-status="Zustellung erfolgreich" recipient-name="Markus Konnertz" recipient-street="Weißenberger Weg 128" recipient-city="41462 Neuss" product-code="00" product-key="" product-name="DHL PAKET" delivery-event-flag="1" recipient-id="1" recipient-id-text="Empfänger (orig.)" international-flag="0" piece-code="00340433957654312359" division="DPEED" pan-recipient-name="Markus Konnertz" pan-recipient-street="Weißenberger Weg 128" pan-recipient-city="41462 Neuss" pan-recipient-address="Weißenberger Weg 128 41462 Neuss" ice="DLVRD" ric="ACCPT" standard-event-code="ZU" shipper-name="Flip4 GmbH" shipper-street="Remscheider Str. 217" shipper-city="42855 Remscheid" shipper-address="Remscheider Str. 217 42855 Remscheid" dest-country="de" origin-country="de" searched-piece-code="00340433957654312359" piece-customer-reference="">
  <data name="piece-event-list" piece-identifier="340433957654312359" _build-time="2011-06-08 07:12:00.000378" piece-id="340433957654312359;1" leitcode="4146214012800">
  <data name="piece-event" event-timestamp="17.05.2011 15:48" event-status="Die Auftragsdaten zu dieser Sendung wurden vom Absender elektronisch an DHL übermittelt." event-text="Die Auftragsdaten zu dieser Sendung wurden vom Absender elektronisch an DHL übermittelt." event-location="" event-country="DE" standard-event-code="VA" ice="PARCV" ric="NRQRD"/>
  <data name="piece-event" event-timestamp="19.05.2011 14:08" event-text="Die Sendung wurde im Start-Paketzentrum bearbeitet." event-status="Die Sendung wurde im Start-Paketzentrum bearbeitet." event-location="Rodgau" event-country="DE" standard-event-code="AA" ice="LDTMV" ric="MVMTV"/>
  <data name="piece-event" event-timestamp="20.05.2011 02:38" event-text="Die Sendung wurde im Ziel-Paketzentrum bearbeitet." event-status="Die Sendung wurde im Ziel-Paketzentrum bearbeitet." event-location="Krefeld" event-country="DE" standard-event-code="EE" ice="ULFMV" ric="UNLDD"/>
  <data name="piece-event" event-timestamp="20.05.2011 08:02" event-text="Die Sendung wurde in das Zustellfahrzeug geladen." event-status="Die Sendung wurde in das Zustellfahrzeug geladen." event-location="Düsseldorf" event-country="DE" standard-event-code="PO" ice="SRTED" ric="NRQRD"/>
  <data name="piece-event" event-timestamp="20.05.2011 09:56" event-status="Die Sendung wurde erfolgreich zugestellt." event-text="Die Sendung wurde erfolgreich zugestellt." event-location="" event-country="" standard-event-code="ZU" ice="DLVRD" ric="ACCPT"/>
  </data>
  </data>
  </data>
  }
end
